name: Release build MacOS
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        default: '1.0'

run-name: 'Build Pomodachi MacOS: v${{ inputs.version }}'

env:
  GODOT_VERSION: 4.6
  GODOT_PROJECT_LOCATION: src/project.godot
  EXPORT_FOLDER: bin/macOS
  APPLICATION_NAME: Pomodachi

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setting extra variables
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "MAIN_FOLDER=$(pwd)" >> $GITHUB_ENV
          echo "NUM_CORES=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV

      - name: Installing dependencies
        run: |
          brew install scons yasm

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout Godot Engine
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ env.GODOT_VERSION }}-stable
          path: godot

      - name: Compile Godot template
        run: |
          cd godot
          scons platform=macos target=template_release arch=x86_64 production=yes build_profile=../build_profile.gdbuild -j${{ env.NUM_CORES }}
          scons platform=macos target=template_release arch=arm64 production=yes build_profile=../build_profile.gdbuild -j${{ env.NUM_CORES }}

      - name: Create universal binary
        run: |
          cd godot/bin
          lipo -create godot.macos.template_release.x86_64 godot.macos.template_release.arm64 -output godot.macos.template_release.universal

      - name: Prepare Godot editor
        run: |
          wget -q -O godot_macos.zip https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_macos.universal.zip
          unzip godot_macos.zip

      - name: Prepare Godot templates
        run: |
          mkdir -p ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.stable
          wget -q -O godot_export_templates.tpz https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          unzip godot_export_templates.tpz -d ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.stable
          mv ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.stable/templates/* ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.stable/
          cp godot/bin/godot.macos.template_release.universal ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.stable/macos_release.zip

      - name: Update version in config
        run: |
          sed -i '' 's/config\/version="[^"]*"/config\/version="${{ env.DATE }}-release"/' ${{ env.GODOT_PROJECT_LOCATION }}

      - name: Import resources
        run: |
          mkdir -p ${{ env.EXPORT_FOLDER }}
          ./Godot.app/Contents/MacOS/Godot --import ${{ env.GODOT_PROJECT_LOCATION }} --quiet --headless

      - name: Building release
        run: |
          ./Godot.app/Contents/MacOS/Godot --import ${{ env.GODOT_PROJECT_LOCATION }} --quiet --headless --export-release MacOS ${{ env.MAIN_FOLDER }}/${{ env.EXPORT_FOLDER }}/${{ env.APPLICATION_NAME }}.app

      - name: Uploading release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APPLICATION_NAME }}_macos_release_${{ env.DATE }}.zip
          path: ${{ env.MAIN_FOLDER }}/${{ env.EXPORT_FOLDER }}/${{ env.APPLICATION_NAME }}.app
